pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
        strict: smart
