name: CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      #- run: ./sbt clean +test
      - run: gem update --system
      - run: gem install sass
      - run: gem install ruby_dep -v 1.3.1
      - run: gem install public_suffix -v 3.0.3
      - run: gem install jekyll -v 4.0.0
      - run: sudo apt-get update && sudo apt install -y graphviz
      - run: ./sbt "project microsite" makeMicrosite -verbose -debug